# Generated by Django 5.0.2 on 2024-05-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_referral_referred_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='refer_link',
            field=models.CharField(max_length=100),
        ),
    ]
