# Generated by Django 4.2 on 2024-05-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_refer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shopping_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
