# Generated by Django 5.0.6 on 2024-05-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
