# Generated by Django 5.0.6 on 2024-06-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_withdraw_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
