# Generated by Django 5.0.6 on 2024-06-22 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_reset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FundPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Funded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('profle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding', to='base.profile')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack', to='base.fundpackage')),
            ],
        ),
    ]
