# Generated by Django 5.0.6 on 2024-06-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_counter_fundpackage_funded'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.fundpackage'),
            preserve_default=False,
        ),
    ]
