# Generated by Django 5.0.6 on 2024-06-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_profilt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilt',
            new_name='Profit',
        ),
    ]
