# Generated by Django 5.0.6 on 2024-06-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_profilt_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='profits',
            field=models.IntegerField(default=0),
        ),
    ]
